apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-config
  labels:
    app: {{ include "postgresql.name" . }}
    release: {{ .Release.Name | quote }}
data:
  postgresql.conf: |-
{{ .Files.Get "postgresql.conf" | indent 4}}
  pg_hba.conf: |-
{{ .Files.Get "pg_hba.conf" | indent 4}}