{{- if .Values.telegraf_sidecar.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "telegraf-sidecar.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "telegraf-sidecar.name" . }}
    helm.sh/chart: {{ include "telegraf.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  telegraf.conf: |+
    [global_tags]
    namespace = "${KUBE_NAMESPACE}"
    {{ template "agent" .Values.telegraf_sidecar.config.agent }}
    {{ template "processors" .Values.telegraf_sidecar.config.processors }}
    {{ template "outputs" .Values.telegraf_sidecar.config.outputs }}
    {{ template "inputs" .Values.telegraf_sidecar.config.inputs -}}
    {{- end}}
